DROP TABLE IF EXISTS user_group;
DROP TABLE IF EXISTS join_request;
DROP TABLE IF EXISTS group_roles;
DROP TABLE IF EXISTS groups_table;

CREATE TABLE groups_table
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(255) NOT NULL,
    description        VARCHAR(1000),
    cover_image_url    VARCHAR(2048),
    group_type         VARCHAR(10)  NOT NULL,
    owner_id           BIGINT       NOT NULL,
    created_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_group
(
    group_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    PRIMARY KEY (group_id, user_id),
    FOREIGN KEY (group_id) REFERENCES groups_table (id)
);

CREATE TABLE join_request
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    status   VARCHAR(10) NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups_table (id)
);

CREATE TABLE group_roles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_type VARCHAR(50) NOT NULL,
    group_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups_table (id) ON DELETE CASCADE
);

COMMIT;
