jwt:
  secret:
    access: LejjnLZua6SlR7eZXByD2+9M5P+dYxK3IlfA6XgPksuXijiXMAcpulI03o2Vq+PjYENhgTJGXLNm7YS4f1+IMw==
    refresh: cRO8f7Q/HaE/X1QjxAHYL8Dm5qkTI68WiNi9elE1NFqsL2up0RlZn/e7aD2R5i8cMvCksBEDhUAOZAhsypQaXw==
server:
  error:
    path: /error
  port: 8095
spring:
#  config:
#    import: optional:file:./friend-service/.env[.properties]

#  kafka:
#    producer:
#      bootstrap-servers: http://kafka:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    topics:
#      friend_changes: friend_changes

  h2:
    console:
      enabled: true
      settings:
        trace: false
#logging:
#  level:
#    org: off
#    com: off
logging:
  level:
    org.hibernate: DEBUG
    org.springframework.orm.jpa: DEBUG
---
spring:
  profiles:
    active: prod
---
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:/temp/data/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: none
  config:
    activate:
      on-profile: dev
---
spring:
  sql:
    init:
      mode: never
      data-locations: classpath:data-postgres.sql
      schema-locations: classpath:schema-postgres.sql
  datasource:
#    url: jdbc:postgresql://${HOST}:5432/postgres?currentSchema=public
    url: jdbc:postgresql://danit-facebook-project.cdw0cecwmddw.us-east-1.rds.amazonaws.com:5432/friends?currentSchema=friends
    username: postgres
    password: danit-final-project-2024
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    #      ddl-auto: update // create // create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
    show-sql: false
  config:
    activate:
      on-profile: prod
gateway:
  url: http://localhost:9090