jwt:
  secret:
    access: LejjnLZua6SlR7eZXByD2+9M5P+dYxK3IlfA6XgPksuXijiXMAcpulI03o2Vq+PjYENhgTJGXLNm7YS4f1+IMw==
    refresh: cRO8f7Q/HaE/X1QjxAHYL8Dm5qkTI68WiNi9elE1NFqsL2up0RlZn/e7aD2R5i8cMvCksBEDhUAOZAhsypQaXw==
spring:
  application:
    name: auth-service
server:
  port: 9080

logging:
  level:
    org: info
    com: off

---

spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: facebookappdanit@gmail.com
    password: ybiy sywv xorc dicf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false
---

spring:
  profiles:
    active: prod

# Local profile configuration
---
spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:data
    username: root
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: false
    show-sql: true
  liquibase:
    enabled: false


# Production profile configuration
---
spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:./auth-service/.env[.properties]
#  flyway:
#    enabled: false
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
#      schema-locations: classpath:schema-postgres.sql
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 100000
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}
#  jpa:
#    open-in-view: false
#    defer-datasource-initialization: true
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        generate_statistics: false
#    show-sql: false
  logging:
    level:
      org: info
      com: off


server:
  port: ${APP_PORT}
gateway:
  url: ${GATEWAY_URL}