version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  minio-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: auth-service
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - '9080:9080'

