version: '3'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
    container_name: massaging
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - '8082:8082'