version: '3.4'

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  kafka_data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: kafka-consumer
    depends_on:
      - kafka
    env_file:
      - .env
    ports:
      - "8084:8084"

  kafka:
    image: bitnami/kafka:latest
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
