version: '3'

networks:
  app-network:
    driver: bridge


services:
  app:
    build:
      context: .
    container_name: newsfeed
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - '8081:8081'
